FROM php:8.3-fpm

RUN apt-get update && apt-get install -y \
    libpq-dev \
    libzip-dev \
    zip \
    unzip \
    nginx \
    supervisor \
    && docker-php-ext-install pdo pdo_pgsql pgsql

COPY nginx.conf /etc/nginx/sites-available/default
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY . /app

RUN echo "DB_USER=${DB_USER}" > .env && \
    echo "DB_PASSWORD=${DB_PASSWORD}" >> .env && \
    echo "APP_URL=${APP_URL}" >> .env && \
    echo "dsn=${dsn}" >> .env

RUN chown -R www-data:www-data /app && \
    mkdir -p /var/run/php && \
    chown www-data:www-data /var/run/php

EXPOSE 80

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
